version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: react-app
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
