services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - chat-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"  # Porta do Mongo Express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb  # Nome do serviço Mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: "" # Desabilitar autenticação MongoDB
      ME_CONFIG_MONGODB_ADMINPASSWORD: "" # Desabilitar autenticação MongoDB
      ME_CONFIG_BASICAUTH_USERNAME: ""  # Desabilitar autenticação básica
      ME_CONFIG_BASICAUTH_PASSWORD: ""  # Desabilitar autenticação básica
      ME_CONFIG_OPTIONS_EDITORTHEME: "default" # Tema do editor
      ME_CONFIG_REQUEST_SIZE: "100kb" # Tamanho máximo da requisição
      ME_CONFIG_SITE_BASEURL: "/" # URL Base
      ME_CONFIG_SITE_SSL_ENABLED: "false" # SSL Desativado
    networks:
      - chat-network

  nodejs:
    build: ./server
    container_name: nodejs-server
    ports:
      - "3003:3003"  # Porta do servidor Node.js
    depends_on:
      - mongo
    networks:
      - chat-network

  react:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:80"
    networks:
      - chat-network

volumes:
  mongo-data:

networks:
  chat-network:
    driver: bridge
