services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - forum-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"  # Porta do Mongo Express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb  # Nome do serviço Mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: "" # Desabilitar autenticação MongoDB
      ME_CONFIG_MONGODB_ADMINPASSWORD: "" # Desabilitar autenticação MongoDB
      ME_CONFIG_BASICAUTH_USERNAME: ""  # Desabilitar autenticação básica
      ME_CONFIG_BASICAUTH_PASSWORD: ""  # Desabilitar autenticação básica
      ME_CONFIG_OPTIONS_EDITORTHEME: "default" # Tema do editor
      ME_CONFIG_REQUEST_SIZE: "100kb" # Tamanho máximo da requisição
      ME_CONFIG_SITE_BASEURL: "/" # URL Base
      ME_CONFIG_SITE_SSL_ENABLED: "false" # SSL Desativado
    networks:
      - forum-network

  nodejs:
    build: ./server
    container_name: nodejs-server
    ports:
      - "3003:3003"  # Porta do servidor Node.js
    depends_on:
      - mongo
    networks:
      - forum-network

  react:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:80"
    networks:
      - forum-network

  dotnet:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dotnet-api
    ports:
      - "5011:5011"
    environment:
      # Connection Strings
      - ConnectionStrings__DefaultConnection=Server=192.168.31.9;Database=PROD;User Id=ronaldo.buscarini;Password=@R7b9rb16@;TrustServerCertificate=True;
      - ConnectionStrings__EntityConnection=Server=192.168.31.144;Database=INTRANET;User Id=ronaldo.buscarini;Password=@R7b9rb16@;TrustServerCertificate=True;
      
      # Kestrel HTTP URL
      - Kestrel__Endpoints__Http__Url=http://0.0.0.0:5011
      
      # SMTP Settings
      - SmtpSettings__User=mailer@purifarma.com.br
      - SmtpSettings__Password=@m6p9mp15@
      - SmtpSettings__Server=smtp.office365.com
      - SmtpSettings__Port=587
      - SmtpSettings__EnableSsl=true
      
      # JWT Settings
      - Jwt__Key=fedaf7d8863b48e197b9287d492b708e
      - Jwt__Issuer=https://api.forum-funcionario.com
      - Jwt__Audience=https://api.forum-funcionario.com
      
      # Allowed Hosts
      - AllowedHosts=*
    networks:
      - forum-network

volumes:
  mongo-data:

networks:
  forum-network:
    driver: bridge
